### ISSUE TITLE
'Jade' option not working

### ISSUE THREAD

**Issue by LuxDie** [ludohenin/gulp-inline-ng2-template#14]
Hi. I'm building a project based off `angular2-seed`. I've deleted a few `.html` files and replaced them with `.jade` files, then added the `jade: true` option to the config object. Running `npm test` throws an error from this plugin, complaining it can't find the `.html` versions of the files.
Am I doing something wrong?

**Comment by ludohenin** [comment]
Can you try to pass `html: false` ?

**Comment by LuxDie** [comment]
When I pass `html: false` it ignores templates altogether (leaves the `templateUrl`).

**Comment by ludohenin** [comment]
fixed by #20
