### ISSUE TITLE
Remove line breaks from html

### ISSUE THREAD

**Issue by amb-it-ion** [ludohenin/gulp-inline-ng2-template#17]
After inlining my compiler will give me incorrect line numbers for the js file, since the include has added new lines. it would be nice to have an option to take out all line breaks, effectively moving all html into one line and allowing the debugger to still work.

**Comment by ludohenin** [comment]
Fixed by #19

**Comment by amb-it-ion** [comment]
Perfect - thanks a lot, keep up the great work!
