### ISSUE TITLE
Feature Request - Resolve variables in .scss file

### ISSUE THREAD

**Issue by ghpabs** [ludohenin/gulp-inline-ng2-template#28]
**Do you want to request a feature or report a bug?**
Feature request.

**What is the current behavior?**
SCSS is transpiled to CSS but the variables aren't resolved. See images below.

*foo.scss*
![image](https://cloud.githubusercontent.com/assets/3250667/13915257/85a05e2c-ef4b-11e5-8adf-15dcdabbd7a9.png)

*DOM*
![image](https://cloud.githubusercontent.com/assets/3250667/13915202/206e8f24-ef4b-11e5-9bb8-28839f9a379a.png)

**Expected behavior**
Resolve variables from the imported partial SCSS.

---

Is it something you'd like to support? Feel free to close the ticket if it's out of scope.

**Comment by ludohenin** [comment]
@ghpabs I don't think this pertains to the plugin.
