### ISSUE TITLE
Excluding node_modules Or Other Files from Inline

### ISSUE THREAD

**Issue by dawsontoth** [ludohenin/gulp-inline-ng2-template#32]
What do y'all think about having an option to ignore (not-inline) based on the path? For example, in my project, I didn't want to try to inline the templates from several TS files in my node_modules. I worked around this by using the parser directly:

```javascript
.pipe(through.obj(function(file, enc, cb) {
	if (file.base.indexOf('node_modules') === -1) {
		file.contents = new Buffer(require('gulp-inline-ng2-template/parser')(file, {
			base: './src/'
		}));
	}
	cb();
}))
```

Perhaps adding a `filter` method to options? I'm more than willing to submit a PR with whatever implementation, if y'all think it's a good idea.

**Comment by ludohenin** [comment]
@dawsontoth sounds like a good idea. We could have 2 options `include/exclude` that supports string "contains" or a regexp. Would be awesome if you submit a PR :)

**Comment by dawsontoth** [comment]
Actually, I found an off the shelf way to work around this -- I used gulp-filter instead --

https://github.com/sindresorhus/gulp-filter

-- that let me choose the files I wanted to use inlining on.
