### ISSUE TITLE
TemplateProcessor Jade

### ISSUE THREAD

**Issue by m0tter** [ludohenin/gulp-inline-ng2-template#33]
Can you please provide an example of how to use Templateprocessor to compile a jade file. I've tried a number of plugins such as vinyl-source-stream and gulp-file but I can't work out how to make gulp wait for jade.
`
templateProcessor: function( ext, file ) {
  let html = '';
  return plugins.file('temp', file, {src: true})
  .pipe(plugins.jade())
  .pipe(plugins.tap(f => { html = f.contents.toString(); }));
  return html;
}
`

Thankyou :)

**Comment by ludohenin** [comment]
@m0tter you have an example here https://github.com/ludohenin/gulp-inline-ng2-template/blob/master/test/test.js#L70-L72

**Comment by m0tter** [comment]
That is awesome thanks for the prompt response. I've spent hours looking over your code and it never once dawned on me to look at the tests. Thanks
