### ISSUE TITLE
Supporting promises as return types of style/template processor functions

### ISSUE THREAD

**Issue by kinkoazc** [ludohenin/gulp-inline-ng2-template#35]
Hello,

Great work with this plugin! Currently I'm trying to process the css code with postcss(which has some async plugins), so the result will be a Promise, as opposed to a string. Supporting promises as return types would really help.

Thank you,
k

**Comment by ludohenin** [comment]
@kinkoazc will see what I can do but that's not a small change.

**Comment by ianbelcher** [comment]
@ludohenin I second @kinkoazc's appreciation for this great plugin. Works fantastically. I've also come across this issue today as well though using postcss which works predominantly in an async fashion.

Just checking if you have any plans for implementing this form of functionality in the short term?

Again, thanks for the work so far on this!

**Comment by kinkoazc** [comment]
@ianbelcher Hi! As a temporary solution I've created a PostCSS gulp task that runs before calling the gulp-inline-ng2-template one.

**Comment by ludohenin** [comment]
@kinkoazc @ianbelcher Working on it now.

**Comment by ludohenin** [comment]
Tagged and published as `2.0.0`

**Comment by kinkoazc** [comment]
That's great! Thank you!

**Comment by ianbelcher** [comment]
Thanks @ludohenin. Really appreciate the work!
