### ISSUE TITLE
Feature request - try to minimize included file

### ISSUE THREAD

**Issue by davidgabrichidze** [ludohenin/gulp-inline-ng2-template#36]

**Comment by ludohenin** [comment]
@davidgabrichidze Do you mean minifying the included files ? Because if it is what you mean, you can use the processor functions for that (https://github.com/ludohenin/gulp-inline-ng2-template#preprocessors-configuration)

**Comment by davidgabrichidze** [comment]
Yes, I meant minifying and yes, there is awesome feature 'preporecessors', but as I understood from example, there is need to create another copy of file ('return newFilename;'). 

It would be more comfortable, to have feature in configuration minify=true. Am I wrong that new copy of file is needed?

**Comment by ludohenin** [comment]
Strings are immutable so any changes to the string creates a copy so it doesn't really matter. Also adding minification goes a bit against gulp principle to keep plugin one problem solving only.
Processor function is the place to go here.
