### ISSUE TITLE
Add Support for Relative Imports when Component Uses moduleId

### ISSUE THREAD

**Issue by Mig1st4ck** [ludohenin/gulp-inline-ng2-template#38]
In the Component we can use a moduleId prop to set the relative path of the module.

https://angular.io/docs/ts/latest/api/core/index/ComponentMetadata-class.html#!#moduleId-anchor

this way we can use this syntax.

```
@Component({
  selector: 'some-component',
  moduleId: module.id,
  templateUrl: 'filename.html'
})
class SomeComponent {
}
```

This helps to move components from paths because we don't need to refactor the paths in templateUrl.

**Comment by ludohenin** [comment]
@Mig1st4ck This already supported (read https://github.com/ludohenin/gulp-inline-ng2-template#configuration). You should pass a configuration object to the plugin
```
{
  base: 'path/to/your/app/root/dir',
  useRelativePaths: true
}
```

**Comment by Mig1st4ck** [comment]
But that will change all behavior of the app, so i can't have 1 component with relative URLs and others without it....

**Comment by ludohenin** [comment]
IMO it's better to stay consistant across the app.
You can still open a PR if you wan to add this functionality as an opt-in (say `useModuleID` false by default)
