### ISSUE TITLE
Automatically append extension through some configuration

### ISSUE THREAD

**Issue by devin6391** [ludohenin/gulp-inline-ng2-template#39]
I want to include my template in component like:

templateUrl: "template/mytemplate"

And then pass some configuration while compiling which would automatically read this as:

templateUrl: "template/mytemplate.html"

This will be a cool feature.

**Comment by ludohenin** [comment]
I think #37 will do what you want.

**Comment by ludohenin** [comment]
fixed via ab81cc1e2215f55ef2a42d7214f9e811fdee8c4d
