### ISSUE TITLE
No templateUrl

### ISSUE THREAD

**Issue by tuanquynet** [ludohenin/gulp-inline-ng2-template#40]
It throw exception "Cannot read property 'toString' of undefined" if source file does not have "templateUrl". The app-loader.ts file has content as below:
`
import {provide, Injector} from '@angular/core';
import {HTTP_PROVIDERS, Http} from '@angular/http';
import {
	ROUTER_DIRECTIVES, RouteConfig,
	ROUTER_PROVIDERS
} from '@angular/router';

import {bootstrap} from '@angular/platform-browser-dynamic';
import {APP_BASE_HREF, LocationStrategy, Location, HashLocationStrategy} from '@angular/common';

bootstrap(PortalApplication, [
	ROUTER_PROVIDERS, HTTP_PROVIDERS,
	provide(LocationStrategy, { useClass: HashLocationStrategy }),
	provide(APP_BASE_HREF, { useValue: '/' })
]);
`

**Comment by ludohenin** [comment]
I don't think so. This plugins is used in many project which of course are not only made of components but service as well.
The parser only look for certain patterns other returns the original file.
Can you provide the error output ?
