### ISSUE TITLE
Cannot use variables or constants for 'templateUrl' & 'styleUrls' property in @Component annotation

### ISSUE THREAD

**Issue by happyvig** [ludohenin/gulp-inline-ng2-template#41]
Hi..,

I was trying to use **variables/constants** for 'templateUrl' & 'styleUrls' property in the @Component annotation.

**Example:**
```
let layout: string = window["layout"];        // desktop or mobile or tablet
let styles: string = "app/home/home.component.css";
let template: string = "app/home/partials/" + prefix + "home.component_" + layout + ".html";

@Component({
    selector: "login",
    moduleId: "login.component",
    **templateUrl: template,
    styleUrls: [styles],**
})
export class LoginComponent implements OnInit {
.......
}
```

The library is **not working** with the above mentioned syntax.

**Comment by ludohenin** [comment]
@happyvig Are doing to build the app for all your supported layouts ?
Otherwise, the [`templateFunction`](https://github.com/ludohenin/gulp-inline-ng2-template#template-function) is made for that.
Regarding your styles, not sure if the same function will work, can you give it a try ?

**Comment by happyvig** [comment]
I am not clear on how to use the template function.  

Where should I declare the templateFunction ? 
Is it inside the component class or within the @Component annotation ?
What file name should I pass to that template function, in my case ? 
( I have three html files for the same component class. 
Example: 
login.component_dekstop.html, 
login.component_mobile.html, 
login.component_tablet.html.   All these three files for a single LoginComponent class. )

**Comment by ludohenin** [comment]
Export a function somewhere in a service for instance, use this function for the template and pass a reference of it to the plugin.

**Comment by ludohenin** [comment]
Closing the issue as this is already covered but we can continue the discussion here.
