### ISSUE TITLE
Reduce html size with a html-min, css-min or similar

### ISSUE THREAD

**Issue by lcrodriguez** [ludohenin/gulp-inline-ng2-template#42]
Is there a way either to hook or extend the plugin to minimize the HTML or CSS being injected, or can you provide directions on how to include it?

I would really like to add that feature. 

Great work!

**Comment by ludohenin** [comment]
@lcrodriguez HTML we can't as it lower the tag attributes which are case sensitive in Angular 2. For the CSS, we could but it's more the responsibility of a processor (https://github.com/ludohenin/gulp-inline-ng2-template#preprocessors-configuration)

**Comment by lcrodriguez** [comment]
Okey. But as we have lower-case angular 2 component only that should not be an issue to me.
So I could add some preprocessor logic there for each one. I will investigate. Thanks.

**Comment by lcrodriguez** [comment]
The https://github.com/kangax/html-minifier has a caseSensitive option! :D

**Comment by ludohenin** [comment]
> So I could add some preprocessor logic there for each one

Only one function to minify them all will be good.
Would actually be nice to add that to the doc if succeed in implementing something. Would you share it ?
But I don't think such feature should live in the plugin.

**Comment by ludohenin** [comment]
Btw how do yo deal with `ngFor` for instance ?

**Comment by lcrodriguez** [comment]
Sure, I will share if I got something working!

**Comment by lcrodriguez** [comment]
I can confirm it works fine.

```javascript
.pipe(inlineTemplate({ 
    base: mySrcPath,
    templateProcessor: inlineProcessor
  }))

function inlineProcessor(ext, file) {
  return htmlMinifier.minify(file, {
    collapseWhitespace: true,
    caseSensitive: true,
    removeComments: true,
    removeRedundantAttributes: true
  });
}
```

**Comment by ludohenin** [comment]
Awesome
