### ISSUE TITLE
Doesn't inline templates if the templateUrl uses backticks.

### ISSUE THREAD

**Issue by jtucker** [ludohenin/gulp-inline-ng2-template#44]
This maybe a very, VERY edge case.

I use back ticks for most of my strings in my ng2 app and noticed today building my production scripts that the task wasn't working with them. 

e.g. 
```javascript
@Component({ 
    selector: `message`, 
    templateUrl: `./app/message/message.component.html`, 
    directives: [CORE_DIRECTIVES] 
}) 
export class MessageDetailComponent {
    constructor() { }
}
```

**Comment by ludohenin** [comment]
Yes this is a bit an edge case, the other question is why do you use template string here ??
Feel free to make a PR, it's just a matter of updating the regexp in the parser.

**Comment by ps2goat** [comment]
+1

**Comment by NathanWalker** [comment]
Just ran into this too. Since going back/forth between inline templates using `template` and back ticks and swapping for url, this can definitely bite someone hard and throw them off for days.

It's probably worth updating the regex to solve 👍

**Comment by ludohenin** [comment]
OK, will try find time soon.
