### ISSUE TITLE
Remove baskslash in pattern attribute

### ISSUE THREAD

**Issue by jbouzekri** [ludohenin/gulp-inline-ng2-template#50]
Hi,

It seems that the plugin remove backslash in pattern attributes when inlining the template.

Before :

``` html
<input type="text" [(ngModel)]="search.imei" id="form-imei" class="form-control" pattern="\d+" required />
```

After : 

``` html
<input type="text" [(ngModel)]="search.imei" id="form-imei" class="form-control" pattern="d+" required />
```

Thanks in advance

**Comment by jbouzekri** [comment]
Note : I am currently using this in my package.json `"gulp-inline-ng2-template": "^1.1.2"`. Maybe it has been fixed in a more recent version ?

**Comment by ludohenin** [comment]
I just did the test adding you example to the test suite and this is not caused by the plugin.

**Comment by jbouzekri** [comment]
Strange I use it inside `angular2-seed` project. Let me try extracting a small portion of the code to see if I am able to reproduce it in a simple example.

**Comment by jbouzekri** [comment]
Hi,

I have created a small repository to demonstrate my issue : https://github.com/jbouzekri/gulp-inline-ng2-template-issue-50

As you can see in the generated [app.component.js file](https://github.com/jbouzekri/gulp-inline-ng2-template-issue-50/blob/master/dist/app/app.component.js), the `\d+` of the pattern attribute is missing the `\`.

And my gulpfile only inline the template and compile it to es5.

I have built this example the same way as the angular2-seed repository is built with the same version of typings and dependencies.

Any idea ?

**Comment by ludohenin** [comment]
@jbouzekri thanks for putting this down and this pointer:

> And my gulpfile only inline the template and compile it to es5.

This is actually not the plugin that strips the backslash but typescript. I've tried with your example.
steps:
1. inline the template
2. comment inline plugin
3. backslash as gone

**Comment by jbouzekri** [comment]
Ouch. This is really bad news. Do you think maybe it would work if you inlined the template using another type of string : template literal, single quote, ... ?

**Comment by ashblue** [comment]
I'm also experiencing the same issue with this plugin. Could is be connected to the Mac operating system environment (which I'm compiling with)?

Duplicate at #66

**Comment by jonguan** [comment]
I am noticing the same issue, version 3.0.1

Here are my options:
```
gulp.task('compile:inline', function () {
  var tsResult = gulp.src('dist/app/**/*.ts')
    .pipe(inlineNg2Template(
      {
        base: '/',
        target: 'es5',
        useRelativePaths: true,
        templateFunction: false,
        removeLineBreaks: true
      }))
    .pipe(sourcemaps.init())
    .pipe(gulp.dest('dist/app'))
    .pipe(ts(tscConfig.compilerOptions));
  return tsResult.js
    .pipe(sourcemaps.write("."))
    .pipe(gulp.dest('src/main/resources/static/app'))
    .pipe(gulp.dest('dist/app'));
});
```

And the resulting `.ts` file:  
```
@Component({
    moduleId: module.id,
    selector: 'confirmAddress',
    template: "<div class=\"\">   <form (ngSubmit)=\"saveAddress($event)\"
...
<input type=\"email\" name=\"emailAddress\" [(ngModel)]=\"emailAddress\" required                   id=\"email\" placeholder=\"Email Address\"                  pattern=\"^([0-9a-zA-Z]([-.w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-w]*[0-9a-zA-Z].)+[a-zA-Z]{2,9})$\">
```

2 things of note:
1. Why start the template with a `"` instead of the regular backtick?
2. I see that `"` in the html are now escaped.
3. This is the .ts file, not the compiled js file.

Original html regex:
`pattern=\"^([0-9a-zA-Z]([-.w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-w]*[0-9a-zA-Z].)+[a-zA-Z]{2,9})$\"`

**Comment by mxii** [comment]
> This is actually not the plugin that strips the backslash but typescript. I've tried with your example.
> steps:
> 1. inline the template
> 2. comment inline plugin
> 3. backslash as gone

@ludohenin So you mean its a typescript problem?

**Comment by ludohenin** [comment]
Yes I thought it was but I have to test it again as I think it's wrong :/

**Comment by dougellison** [comment]
This still appears to be an issue.  I've recently updated from Angular2 RC5 to Final and accomplished that by merging the latest seed changes.  My lazy solution has been to run with pattern with a single \ in dev but when I'm happy with its functionality I go through and replace with \ -> \\ and then it works fine in production.

**Comment by tuanquynet** [comment]
I am facing the same problem when I define pattern attribute containing "\" char

**Comment by gregjacobs** [comment]
It seems like this is a general issue @ludohenin where backslashes in html files need to be escaped for when they are placed into string literals inside JavaScript.

JavaScript would interpret the string literal `"\d"` in code to simply be the string `'d'`. (`"\d"` is not a valid escape in JS strings like say, `"\n"` is, so it ends up just being the letter itself)

We basically need to convert this html:

```html
<input pattern="\d+">
```

To the following JavaScript:

```js
@Component({
    template: `<input pattern="\\d+">`
})
```
