### ISSUE TITLE
Issue when using es6 templating

### ISSUE THREAD

**Issue by GuillaumeRahbari** [ludohenin/gulp-inline-ng2-template#53]
Hello,

I have this issue, in my html I have an expression like this :
`${{myVariable}}`

I need this because I want a dollars preceding myVariable interpreted.

But when I do the inline templating I got an error because in the typescript file the '${}' is interpreted as an es6 templating syntax (that is kinda logic).

Do you know how should I escape this ? Or maybe you have an other solution.

PS : I'm doing the inline templating in my typescript files, so before it has been compiled. Maybe the inline templating should be done after the compilation ?

Thanks for your help !
Guillaume Rahbari

**Comment by xr0master** [comment]
You can escape it.
<span>$</span>{{myVariable}}
or any tag

**Comment by ludohenin** [comment]
Can we close ?

**Comment by GuillaumeRahbari** [comment]
Yes thank you :)
