### ISSUE TITLE
not working with relative template files (using module.id)

### ISSUE THREAD

**Issue by Velavok** [ludohenin/gulp-inline-ng2-template#54]
Hello!
I have a component with extracted tempate and styles. I use moduleId property because i don't want to write full path to files. 
Running gulp task i recieve an error about not founding template file in root directory.

var module: any;

@Component({
	moduleId: module.id,
	selector: 'promo',
	templateUrl: 'promo.component.html',
	styleUrls: ['promo.component.css']
})

**Comment by ludohenin** [comment]
Is useRelativePaths option turned on ?
https://github.com/ludohenin/gulp-inline-ng2-template#options

**Comment by Velavok** [comment]
Yes.
Here is gulp task:

`gulp.task("inlineTempaltes", () => {
	var result = gulp.src('./TScript/**/*.ts')
		.pipe(inlineNg2Template({
			base: '/TScript',
			useRelativePaths: false
		}));

	return result
		.pipe(gulp.dest('/tapp'));
});
`

files Tree looks like this:
![image](https://cloud.githubusercontent.com/assets/2556514/17456017/a3b5532e-5bd2-11e6-8cd7-74cb0db40af4.png)

And I am getting this error:
fs.js:634
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT: no such file or directory, open 'C:\...\TScript\base.component.html'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
