### ISSUE TITLE
Add includePaths options

### ISSUE THREAD

**Issue by tamascsaba** [ludohenin/gulp-inline-ng2-template#56]
It will be good if you can add includePaths options like node-sass [includePaths](https://github.com/sass/node-sass#includepaths)

First file match win :)
 
Example:
```
{
 useRelativePaths: true,
  includePaths: ['node_modules', 'src/styles']
}
```
```
styleUrls: [
    'bootstrap/scss/bootstrap.scss',
    'hint.css/src/hint.scss',
    'app.style.scss',
  ],

```

**Comment by ludohenin** [comment]
I'm not sure to fully understand. If `useRelativePaths ` is true then it means the file is living next to the component file otherwise it's a fully qualified path.

Or is it that you'd like to have a mix of relative and "absolute" paths ?

**Comment by ludohenin** [comment]
Btw, you should be able to add this behavior using the `CustomFilePath` configuration option.

**Comment by tamascsaba** [comment]
Yes :+1:
