### ISSUE TITLE
customFilePath is receiving an array instead of an string

### ISSUE THREAD

**Issue by rduenasf** [ludohenin/gulp-inline-ng2-template#59]
`exec` here: https://github.com/ludohenin/gulp-inline-ng2-template/blob/master/parser.js#L278

returns an array, this is being passed into `customFilePath` but it expects an `string`

**Comment by rduenasf** [comment]
This is also happening here: 

https://github.com/ludohenin/gulp-inline-ng2-template/blob/master/parser.js#L247

**Comment by ludohenin** [comment]
Good catch, would you make a PR for that ?
