### ISSUE TITLE
support styleUrls

### ISSUE THREAD

**Issue by werenskjold** [ludohenin/gulp-inline-ng2-template#6]
it would have been useful if this module supported inline styles

**Comment by ludohenin** [comment]
@werenskjold Yes I know. I'm actually working on a gulp-inline-styles plugin.
Will close this issue when it is published to npm.

**Comment by ludohenin** [comment]
@werenskjold it is here [https://github.com/ludohenin/gulp-inline-ng2-styles](https://github.com/ludohenin/gulp-inline-ng2-styles)

**Comment by ludohenin** [comment]
@werenskjold I will deprecate gulp-inline-ng2-styles. Style sheets support's been added to this plugin.

**Comment by werenskjold** [comment]
thanks :)
