### ISSUE TITLE
Parser has no error handling

### ISSUE THREAD

**Issue by tamascsaba** [ludohenin/gulp-inline-ng2-template#60]
In [parser.js](https://github.com/ludohenin/gulp-inline-ng2-template/blob/master/parser.js#L73) always return with `null`

**Comment by enanox** [comment]
@ludohenin passing the `err` to the callback was omitted for performance issues on the async process?

**Comment by tamascsaba** [comment]
@ludohenin ????

**Comment by ludohenin** [comment]
I'll fix that ASAP.

**Comment by tamascsaba** [comment]
@ludohenin ???

**Comment by ludohenin** [comment]
would you please make a PR ?

**Comment by gregjacobs** [comment]
Hey, raised this as well in #73. Fixed in PR #75

**Comment by tamascsaba** [comment]
@gregjacobs thx :+1:
