### ISSUE TITLE
component inline problem 

### ISSUE THREAD

**Issue by msahamed** [ludohenin/gulp-inline-ng2-template#62]
If I import a template  in a component like :
               templateUrl :"../app.component.html"

and the app.component.html contains some html with other components :

<header-component>
<p>
  Hello {{ world }}
</p>
<footer-componet>

I was wondering if the "gulp-inline-ng2-template" can also import inner codes of <header-component> and <footer-componet> and inline them with other codes ?

**Comment by ludohenin** [comment]
Not sure to understand what's your problem @msahamed
