### ISSUE TITLE
Is it ok I cannot have <script> in the templates?

### ISSUE THREAD

**Issue by zverevalexei** [ludohenin/gulp-inline-ng2-template#64]
Hi Ludovic,

Basically I'm trying to reinvent the wheel, cuz I wanted to practice with Angular2 and TypeScript a little bit. One of the examples I saw, used this lib as a part of solution. I went for it, but I suddenly ended up suspecting that the templates were processed in one or another way... And no scripts inside the script tag (which goes in one of the templates) work.

Here's the [source template file](https://github.com/zverevalexei/usa-legal-map/blob/master/dev/frontend/app/templates/home.tpl.html).

Here's the result of the entire compilation: [build](https://github.com/zverevalexei/usa-legal-map/tree/master/build/public)

And this fat guy is where the whole Angular app along with the templates sits: [app.bundle.js](https://raw.githubusercontent.com/zverevalexei/usa-legal-map/master/build/public/js/app.bundle.js)

If you would search on page for "map = new Datamap", you'll run into the script's body. It is there, but it's not working.

Here's my [Gulpfile](https://github.com/zverevalexei/usa-legal-map/blob/master/dev/gulpfile.js#L134), too.

Like I said, the problem is that the content of the script tag above does not run, therefore you cannot see the USA map... Hope you'll give a heads-up.

Thanks a lot!!!

P. S. not sure if there's something like your library out there for Angular 1, but I was looking for it =)

**Comment by ludohenin** [comment]
Isn't it just the way Angular compiles templates ?
Can you try inlining this template yourself in your component file and see if it's coming from the plugin ?

**Comment by zverevalexei** [comment]
@ludohenin 
Didn't expect that. Do you happen to know the reason? 
Thanks

**Comment by gogamwar** [comment]
@zverevalexei See https://github.com/angular/angular/issues/4903

**Comment by zverevalexei** [comment]
@gogamwar thanks!
