### ISSUE TITLE
HTML5 pattern attribute is mangled

### ISSUE THREAD

**Issue by ashblue** [ludohenin/gulp-inline-ng2-template#66]
On our application a pattern such as `<input pattern="\d{2}\s\-\s\d{2}\s\-\s\d{4}" ...` is being mangled into `<input pattern="d{2}s-sd{2}s-sd{4}" ...` immediately upon conversion. Any way to prevent this? Maybe some kind of custom options I don't know about?

**Comment by ludohenin** [comment]
looks like a duplicate of #50

**Comment by ashblue** [comment]
Duplicate of #50
