### ISSUE TITLE
Some functions swallows error

### ISSUE THREAD

**Issue by unlight** [ludohenin/gulp-inline-ng2-template#68]
Which prevents catching.

See comments.
```js
  function processStyles(done) {
    if (opts.styleProcessor) {
      CSS = true;
      extend(opts, cssOptions());
      execute(function () { // First argument is error, it should be forwarded to done()
        reset();
        done(null);
      });
    }
  }
```
Same in other functions:
https://github.com/ludohenin/gulp-inline-ng2-template/blob/master/parser.js#L82
https://github.com/ludohenin/gulp-inline-ng2-template/blob/master/parser.js#L72

**Comment by ludohenin** [comment]
this is a duplicate of #60
