### ISSUE TITLE
Support for Angular2 Final

### ISSUE THREAD

**Issue by mohuk** [ludohenin/gulp-inline-ng2-template#69]
```typescript
import {Component, View} from 'angular2/angular2';
@Component({ selector: 'app' })
@View({
  template: `
    <p>
      Hello {{ world }}
    </p>
  `,
  styles: [`
    .hello {
      color: red;
    }
  `],
  directives: [CORE_DIRECTIVES]
})
class AppCmp {}
```

The example shows older decorators, does this work with Angular2 Final?

**Comment by RoxKilly** [comment]
It does work with final.

I have run into bug #67 though: If your external template has a dollar sign in front of an open bracket, this plugin will fail:
```
${{amount}}
```

Otherwise, it's working well for me.

**Comment by ludohenin** [comment]
This is working wekk with ng2 final.
