### ISSUE TITLE
remove moduleId

### ISSUE THREAD

**Issue by gforceg** [ludohenin/gulp-inline-ng2-template#71]
One of the reason's I am using this plugin is to that I can write my code using separate files: an html template, a css stylesheet, and a typescript component file, and then output those files in a way that works w/ gulp and webpack.

Webpack doesn't like moduleIds so I end up w/ errors when I bring my libraries into an angular-cli project.

I'd like to add a boolean option to remove moduleIds from the resulting inlined typescript component.

Is this something that you'd consider merging if I sent submitted a PR?

**Comment by gforceg** [comment]
It turns out I can just leave out the moduleIds in my source (or comment them out) and use the `useRelativePaths` option.
So maybe this is an unnecessary feature?

**Comment by cgatian** [comment]
@gforceg I was curious if you found a better approach to building modules with Webpack?

**Comment by gforceg** [comment]
No. I have a base project and a custom CLI I've created.

The base project uses GULP and can be found here: [ng2-base](https://github.com/gforceg/ng2-base)

The CLI does not work well on MS Windows, but it can be found here: [ng-](https://github.com/gforceg/ng-)

But no, I haven't done the dive into Webpack yet.
