### ISSUE TITLE
Parser Error: Unexpected end of input

### ISSUE THREAD

**Issue by ezforms** [ludohenin/gulp-inline-ng2-template#72]
When I try to build for production in my Angular2 App using this [seed](https://github.com/mgechev/angular-seed), I get the following error.

/node_modules/gulp-inline-ng2-template/parser.js:188
_urls = eval('({' + frag + '})')[opts.prop_url];
^
SyntaxError: Unexpected end of input

I dont even know where to look. Any guidence or what its trying to do at that point would be helpful.

**Comment by ludohenin** [comment]
You probably have an issue with one of you component decorator options.

**Comment by ezforms** [comment]
Thanks. Is it more likely to be pathing to html template or inline html?

**Comment by ezforms** [comment]
@ludohenin I found the issue. I had a styleUrls that was an empty array. So either is didnt like that it was empty or was trying to read the commented out style.

    styleUrls: [
        // load the default theme
        //'@telerik/kendo-theme-default/dist/all.css'
    ],

**Comment by renestalder** [comment]
Nice one. Had the same issues. Thanks for pointing this out, @ezforms. Could this be improved, either with a better error message or by ignoring empty styleUrls?
