### ISSUE TITLE
Support removing `moduleId` from parsed templates

### ISSUE THREAD

**Issue by ovangle** [ludohenin/gulp-inline-ng2-template#80]
I was looking at this library to possibly use as a prepublish script for a component library.

There is a problem with developing component libraries if the templates are kept in separate files from the components. Consumers of the library which use SystemJS expect a `moduleId` on the component definition, but webpack uses numeric `moduleId`s, which break the angular compiler.

Once templates have been inlined, angular makes no further use of the component's `moduleId` anyway, so it would cause very little pain if there was an option to remove it as part of the gulp plugin. 

See `@angular/material2/scripts/inline-resources.ts` (file name off the top of my head) for an example of this in the wild.

The general plan would be to add an option to the plugin `removeModuleId` (default `true`) to the options. 

I can have a PR ready sometime tomorrow if this sounds OK with you.

Thanks!

**Comment by haykanushT** [comment]
Hi @ovangle .
I am facing the same problem as described in your issue.
DId you manage to find a solution to "removing moduleId" problem?

**Comment by ludohenin** [comment]
Fixed by #81
