### ISSUE TITLE
Contributors List on Readme

### ISSUE THREAD

**Issue by gregjacobs** [ludohenin/gulp-inline-ng2-template#85]
Hey @ludohenin, apologies for the random question, but how did you get that fancy Contributors list on your readme? Would like to add that to my projects!

Thanks,
Greg

**Comment by ludohenin** [comment]
hi @gregjacobs, here it is https://github.com/mgechev/github-contributors-list
In the readme of this repo, I use an Auth0 webtask to generate a SVG.

**Comment by gregjacobs** [comment]
Thanks @ludohenin. Very clever with the webtask! Much appreciated! 👍 👍
